Repository NorESSI/software-layer, pull requests merged in 2023-03, with the labels that each got.

#34 Adding Nextflow-22.10.1.eb to NESSI/2022.11
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy

#42 Replay PR24 with fix for generic builds
  EESSI-pilot-install-software.sh
  bot/build.sh
  eessi-2022.11.yml
  eessi_container.sh
Labels: bot:build, bot:deploy

#24 Add Qt5/5.14.1 with GCCcore-9.3.0 to NESSI/2022.11
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy

#55 Added the initial 6 essential packages
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy

#61 Sync with NESSI/main which was just sync'ed with EESSI/main
  bot/bot-eessi-aws-citc.cfg
Labels: bot:build

#58 pull in fixes from EESSI/software-layer PR238 and PR239
  EESSI-pilot-install-software.sh
  create_tarball.sh
Labels: bot:build

#63 Sync branch for rebuilding `generic` with branch for NESSI/2022.11
  bot/bot-eessi-aws-citc.cfg
  create_tarball.sh
Labels: bot:build

#64 Sync lmod cache update with NESSI/2022.11
  EESSI-pilot-install-software.sh
  bot/bot-eessi-aws-citc.cfg
  create_tarball.sh
Labels: bot:build

#46 Add OSU-Micro-Benchmarks/5.7.1 with GCC/10.3.0 to NESSI/2022.11
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy

#56 update lmod cache (started mid March 2023)
  EESSI-pilot-install-software.sh
Labels: bot:build, bot:deploy

#65 add CMake 3.16.4 with GCC/9.3.0 for generic architectures
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy, ingested, generic_only

#78 install GCC/10.3.0 & fix easystack file
  EESSI-pilot-install-software.sh
  check_missing_installations.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy, generic_only

#79 ensure that dev branch is healthy
  EESSI-pilot-install-software.sh
  check_missing_installations.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy

#72 add CMake, Python, OpenMPI and ImageMagick with GCC/10.3.0 to NESSI/2022.11 (generic only)
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy, ingested, generic_only

#48 Add WRF/3.9.1.1 with GCC/9.3.0 to NESSI/2022.11
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy

#81 Add SciPy-bundle/2020.03 with GCC/9.3.0 to NESSI/2022.11 (generic only)
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy, rebuild_generic

#83 update lmod cache for generic targets
  EESSI-pilot-install-software.sh
Labels: bot:build, bot:deploy, generic_only, Lmod_cache_update

#84 add missing packages, removed -from-pr or commented EBs out (generic only)
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy, generic_only

#80 Add Qt/5.14.1 with GCC/9.3.0 to NESSI/2022.11 (generic only)
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy, rebuild_generic, ingested

#45 Add OSU-Micro-Benchmarks/5.6.3 with GCC/9.3.0 to NESSI/2022.11
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy

#85 add R/4.0.0 with GCC/9.3.0 to NESSI/2022.11
  EESSI-pilot-install-software.sh
  eessi-2022.11.yml
Labels: bot:build, bot:deploy
